### ISSUE TITLE
URL of template repo

### ISSUE THREAD

**Issue by ymnliu** [nlpsandbox/date-annotator-example-java#25]
From README, under `Development` -> `Creating a new GitHub repository`:

The python template URL is broken.

**Comment by tschaffter** [comment]
@ymnliu I can not find the broken link. Do you mind copy/pasting the sentence that includes the broken link?

**Comment by tschaffter** [comment]
The link works. I added a note that the user has to click on the button `Use this template` once he/she lands on the repository.
