### ISSUE TITLE
Implement date annotation

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/date-annotator-example-java#8]
Implement date annotation by modifying the example code I created [here](https://github.com/nlpsandbox/date-annotator-example-java/blob/develop/server/src/main/java/org/openapitools/api/DatesApi.java#L61-L74)

**Comment by ymnliu** [comment]
@tschaffter Do I have the permission to push on this? I tried to create a new branch but got permission denied.

**Comment by tschaffter** [comment]
You do not have write access to this repo. Did developed the code in your fork of the repository? If yes, you can go to the GitHub page of your fork to create a PR that targets the branch `develop` of this repo.
